# Falcon Dongle - Config
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# USB HID output to computer
CONFIG_ZMK_USB=y

# Pointing / trackball support on the central side
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

# Receive relayed input events from the right peripheral
CONFIG_ZMK_INPUT_SPLIT=y
