# Falcon Right Half - Config
# Split and pointing are set in Kconfig.defconfig
CONFIG_INPUT=y
CONFIG_ZMK_INPUT_SPLIT=y
CONFIG_PMW3610_ALT=y

# nice!nano v2 requires extra VCC stabilisation delay before sensor init.
# Without this you will see "Incorrect product id 0xFF" in logs.
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000
